permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: houzhenhong
  email: houzhenhong@outlook.com
  link: https://houzhenhong.towerlight.top
  weibo: http://weibo.com/
  github: https://github.com/skywalker512

# 站点信息
title: HZH 写东西的地方
description: HOUZHENHONG 写东西的地方
url: https://houzhenhong.towerlight.top
rss_url: /pages/rss.xml

# avatar头像及Favicon
avatar: /site-avatar.png
favicon: /site-favicon.ico

# disqus 设置
disqus:
  shortname: houzhenhong
