permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: houzhenhong
  email: houzhenhong@outlook.com
  link: http://houzhenhong.eu.org
  weibo: http://weibo.com/2771513197
  github: https://github.com/skywalker512

# 站点信息
title: HZH's blog
description: HOUZHENHONG的博客
url: http://houzhenhong.eu.org
rss_url: /pages/rss.xml

# avatar头像及Favicon
avatar: http://dn-hzhblog.qbox.me/site-avatar.png
favicon: http://dn-hzhblog.qbox.me/site-favicon.ico

# disqus 设置
disqus:
  shortname: houzhenhong
